/**
 * Courtesy of:
 * - http://laffgaff.com/funny-burn-jokes/
 * - https://thoughtcatalog.com/melanie-berliet/2016/02/50-hilarious-comebacks-that-will-shut-everyone-up-and-make-you-look-like-a-genius/
 */

module.exports = [
  `You'd need twice the brains to qualify as a half-wit.`,
  `You have the face of a saint. A Saint Bernard, that is.`,
  `What you lack in intelligence, you more than make up for in stupidity.`,
  `You're listed in Who's Who as What's That.`,
  `God wasted a good asshole when he put teeth in your mouth.`,
  `I couldn't stop thinking about you all day today. I was at the zoo.`,
  `Are you always so stupid or is today a special occasion?`,
  `You need to shut your mouth 'cause all your stupidity is leaking out.`,
  `Have you been shopping lately? They're selling lives - you should go get yourself one.`,
  `You're so ugly you'd scare the crap out of the toilet.`,
  `I heard you were born on a farm. Any more in the litter?`,
  `Everyone has the right to be stupid, but you're just abusing the privilege.`,
  `I wouldn't pee in your ear if your brain was on fire.`,
  `If I had a face like yours, I'd teach my ass to talk.`,
  `Don't feel bad. A lot of people have no talent.`,
  `I couldn't warm to you if you were on fire.`,
  `Just let people think you're an idiot. If you say anything, you'll just prove them right.`,
  `As an outsider, what do you think of the human race?`,
  `You don't need some beauty sleep, you need to hibernate.`,
  `People like you don't grow on trees. They swing from them.`,
  `I sure hope there's a lifeguard in your gene pool.`,
  `Go ahead and tell me everything you know. I've got a spare ten seconds.`,
  `Every time I think of all the people that haven't met you, I get jealous.`,
  `You're so far up your own ass you can lick your tonsils.`,
  `Some people bring joy wherever they go. You bring joy whenever you go.`,
  `You've got a face that could turn fresh milk sour.`,
  `Stop thinking everyone's your equal. That's offensive to a lot of people.`,
  `A lot of people live and learn. You just live.`,
  `You remind me of myself. Back when I was young and stupid.`,
  `You've got a face like a bag of elbows.`,
  `I don't want you to turn the other cheek - it's just as ugly.`,
  `What drugs are you on, stupid pills?`,
  `Let's go to the zoo. I've always wanted to meet your family.`,
  `A half-wit gave you a piece of his mind, and you held on to it.`,
  `Last time I saw something like you, I flushed it.`,
  `It's too bad stupidity isn't painful.`,
  `You're as strong as an ox. Just not as intelligent.`,
  `Come again when you can't stay as long.`,
  `People like you are the reason God doesn't talk to us anymore.`,
  `You're kind of like Rapunzel but instead of letting your hair down, you let everyone down in your life.`,
  `You have your entire life to be a jerk. Why not take today off?`,
  `Your ass must be pretty jealous of all the shit that comes out of your mouth.`,
  `Remember when I asked for your opinion? Me neither.`,
  `If you’re waiting for me to care, I hope you brought something to eat, ‘cause it’s gonna be a really long time.`,
  `Some day you’ll go far—and I really hope you stay there.`,
  `I’m trying my absolute hardest to see things from your perspective, but I just can’t get my head that far up my ass.`,
  `Sometimes it’s better to keep your mouth shut and give the impression that you’re stupid than open it and remove all doubt.`,
  `I’m not a proctologist, but I know an asshole when I see one.`,
  `You only annoy me when you’re breathing, really.`,
  `Do yourself a favor and ignore anyone who tells you to be yourself. Bad idea in your case.`,
  `I don’t know what your problem is, but I’m guessing it’s hard to pronounce.`,
  `Do your parents even realize they’re living proof that two wrongs don’t make a right?`,
  `Remember that time I said I thought you were cool? I lied.`,
  `Everyone’s entitled to act stupid once in awhile, but you really abuse the privilege.`,
  `I can’t help imagining how much awesomer the world would be if your dad had just pulled out.`,
  `Do you ever wonder what life would be like if you’d gotten enough oxygen at birth?`,
  `Please, save your breath. You’ll probably need it to blow up your next date.`,
  `Can you die of constipation? I ask because I’m worried about how full of shit you are.`,
  `Good story, but in what chapter do you shut the fuck up?`,
  `Don’t hate me because I’m beautiful. Hate me because your boyfriend thinks so.`,
  `Were you born on the highway? That is where most accidents happen.`,
  `Please, keep talking. I only yawn when I’m super fascinated.`,
  `If I wanted to hear from an asshole, I’d fart.`,
  `Jesus might love you, but everyone else definitely thinks you’re an idiot.`,
  `Sorry, I didn’t get that. I don’t speak bullshit.`,
  `The only way you’ll ever get laid is if you crawl up a chicken’s ass and wait.`,
  `If ignorance is bliss, you must be the happiest person on the planet.`,
  `Are you always such an idiot, or do you just show off when I’m around?`,
  `There are some remarkably dumb people in this world. Thanks for helping me understand that.`,
  `I could eat a bowl of alphabet soup and shit out a smarter statement than whatever you just said.`,
  `I was pro life. Then I met you.`,
  `You’re about as useful as a screen door on a submarine.`,
  `Whenever we hang out, I remember that God really does have a sense of humor.`,
  `It’s kind of hilarious watching you try to fit your entire vocabulary into one sentence.`,
  `Please just tell me you don’t plan to home-school your kids.`,
  `You always bring me so much joy—as soon as you leave the room.`,
  `I was hoping for a battle of wits but it would be wrong to attack someone who’s totally unarmed.`,
  `I’d tell you how I really feel, but I wasn’t born with enough middle fingers to express myself in this case.`,
  `Stupidity’s not a crime, so feel free to go.`,
  `I’d tell you to go fuck yourself, but that would be cruel and unusual punishment.`,
  `The village called. They’d like their idiot back. You better get going.`,
  `You have the right to remain silent because whatever you say will probably be stupid anyway.`,
  `Your family tree must be a cactus ‘cause you’re all a bunch of pricks.`,
  `I was going to give you a nasty look but I see that you’ve already got one.`,
  `You’re about as useful as an ashtray on a motorcycle.`,
  `People like you are the reason I’m on medication.`,
  `I believed in evolution until I met you.`,
  `If I threw a stick, you’d leave, right?`,
  `You’ll never be the man your mom is.`,
  `Earth is full. Go home.`
];